### ISSUE TITLE
colocar link de video de secure service en la opcion de videos 

### ISSUE THREAD

**Issue by edymac** [MASTERPC-CIA/secure_service#1]
te envio el link para que lo subas en secure service https://www.youtube.com/watch?v=ocRNFWrzDL0
hay 3 videos unos de ellos hay que cambiar ..

**Comment by edymac** [comment]
No olvidar de hacer el listado de las garantias registradas...

**Comment by angelvcuenca** [comment]
Cumplire con los requisitos a mas tarde el dia Lunes, este fin de semana acomadare toda la parte de llaves y vista de imprimir garantias

**Comment by edymac** [comment]
SOLO date un tiempo para que cambies el link del video promocional ..

**Comment by angelvcuenca** [comment]
La pagina se encuentra lista Ing. los requerimiento que me solicito que haga ya se encuentran efectuados, se agrego el video solicitado, cambio en el modulo ->  model , controllers , view para llevar a cabo el requerimiento de enviado de correo electronico e imprimir la solicitud de garantia, el modulo de garantia realiza todo el CRUD correspondiente.
